import ballerina/grpc;
import ballerina/uuid;
import ballerina/log;
import ballerina/time;

// NOTE: Property, PropertyResponse, User, etc. and the *Caller types below
// are generated by `bal grpc --input rental.proto --output .`
// Match this file's names to whatever the generated _pb.bal stub calls them.

map<Property> properties = {};   // keyed by property_id
map<Booking> bookingCart = {};   // pending bookings, keyed by booking_id
map<Booking> confirmedBookings = {}; // keyed by booking_id
map<User> users = {};            // keyed by user_id

int propertyCounter = 0;
int bookingCounter = 0;

// KEEP THIS FUNCTION HERE
function nightsBetween(string checkIn, string checkOut) returns int|error {
    time:Utc inUtc = check time:utcFromString(
        checkIn + "T00:00:00.00Z"
    );

    time:Utc outUtc = check time:utcFromString(
        checkOut + "T00:00:00.00Z"
    );

    decimal diffSeconds = time:utcDiffSeconds(outUtc, inUtc);

    return <int>(diffSeconds / 86400);
}

@grpc:Descriptor {value: RENTAL_DESC}
service "RentalService" on new grpc:Listener(9090) {

     // add_property
remote function add_property(Property req) returns PropertyResponse|error {

    string propertyId = uuid:createType4AsString();

    Property newProperty = {
        property_id: propertyId,
        property_name: req.property_name,
        location: req.location,
        property_type: req.property_type,
        price_per_night: req.price_per_night,
        status: req.status
    };

    properties[propertyId] = newProperty;

    log:printInfo("Property added: " + propertyId);

    return {
        property: newProperty,
        message: "Property registered successfully"
    };
}



    remote function update_property(Property value) returns PropertyResponse|error {
    Property? existing = properties[value.property_id];

    if existing is () {
        return error("Property with id " + value.property_id + " not found");
    }

    properties[value.property_id] = value;

    log:printInfo("Property updated: " + value.property_id);

    return {
        property: value,
        message: "Property updated successfully"
    };
}

    //  remove_property
remote function remove_property(PropertyIdRequest req) returns PropertyList|error {

    Property? target = properties[req.property_id];

    if target is () {
        return error("Property with id " + req.property_id + " not found");
    }

    string region = target.location;

    _ = properties.remove(req.property_id);

    log:printInfo("Property removed: " + req.property_id);

    Property[] remaining = [];

    foreach Property p in properties {
        if p.location == region && p.status == "AVAILABLE" {
            remaining.push(p);
        }
    }

    return {
        properties: remaining
    };
}

    remote function search_property(PropertyIdRequest value) returns PropertyResponse|error {
    Property? found = properties[value.property_id];

    if found is () {
        return {
            message: "Not Available"
        };
    }

    return {
        property: found,
        message: "Property found"
    };
}

        remote function book_property(BookingRequest value) returns BookingCartResponse|error {
        if value.check_in >= value.check_out {
            return error("check_out (" + value.check_out + ") must be after check_in (" + value.check_in + ")");
        }

        string bookingId = uuid:createType4AsString();

        Booking newBooking = {
            bookingId: bookingId,
            propertyId: value.property_id,
            guestId: value.guest_id,
            checkIn: value.check_in,
            checkOut: value.check_out,
            status: "PENDING"
        };

        bookingCart[bookingId] = newBooking;

        log:printInfo("Booking created: " + bookingId);

        return {
            booking_id: bookingId,
            status: "PENDING"
        };
    }


//confirm a booking
remote function confirm_booking(ConfirmBookingRequest value)
        returns BookingConfirmation|error {

    // 1. Find the booking in the booking cart
    Booking? cart = bookingCart[value.booking_id];

    if cart is () {
        return {
            booking_id: value.booking_id,
            total_cost: 0.0,
            status: "REJECTED"
        };
    }

    // 2. Find the property
    Property? property = properties[cart.propertyId];

    if property is () {
        _ = bookingCart.remove(value.booking_id);

        return {
            booking_id: value.booking_id,
            total_cost: 0.0,
            status: "REJECTED"
        };
    }

    // 3. Check if the property is available
    if property.status != "AVAILABLE" {
        _ = bookingCart.remove(value.booking_id);

        return {
            booking_id: value.booking_id,
            total_cost: 0.0,
            status: "REJECTED"
        };
    }

    // 4. Check that check-out is after check-in
    int nights = check nightsBetween(
        cart.checkIn,
        cart.checkOut
    );

    if nights <= 0 {
        _ = bookingCart.remove(value.booking_id);

        return {
            booking_id: value.booking_id,
            total_cost: 0.0,
            status: "REJECTED"
        };
    }

    // 5. Check for overlapping confirmed bookings
    foreach Booking confirmed in confirmedBookings {

        if confirmed.propertyId == cart.propertyId {

            if cart.checkIn < confirmed.checkOut &&
               cart.checkOut > confirmed.checkIn {

                _ = bookingCart.remove(value.booking_id);

                return {
                    booking_id: value.booking_id,
                    total_cost: 0.0,
                    status: "REJECTED"
                };
            }
        }
    }

    // 6. Calculate total cost
    float totalCost =
        property.price_per_night * <float>nights;

    // 7. Update the booking
    cart.totalCost = totalCost;
    cart.status = "CONFIRMED";

    // 8. Remove booking from cart
    _ = bookingCart.remove(value.booking_id);

    // 9. Add booking to confirmed bookings
    confirmedBookings[value.booking_id] = cart;

    log:printInfo("Booking confirmed: " + value.booking_id);

    // 10. Return confirmation
    return {
        booking_id: value.booking_id,
        total_cost: totalCost,
        status: "CONFIRMED"
    };
}

    // --- Client streaming ---

    remote function create_users(stream<User, grpc:Error?> clientStream) returns UserCreationResponse|error {
        int count = 0;
        check from User u in clientStream
        do{
            users[u.user_id] = u;
            count += 1;
        };
        return {count: count, message: "Registered "+count.toString()+" users successfully."};
    }

    // --- Server streaming ---

    remote function list_available_properties(RentalServicePropertyCaller caller, PropertyFilter value) returns error? {
        foreach Property p in properties {
            boolean matchesLocation = value.location == "" || p.location == value.location;
            boolean matchesPrice = value.max_price == 0.0 || p.price_per_night <= value.max_price;
            if (matchesLocation && matchesPrice && p.status == "AVAILABLE") {
                check caller->sendProperty(p);
            }
        }

        check caller->complete();
    }
}