import ballerina/grpc;

// NOTE: Property, PropertyResponse, User, etc. and the *Caller types below
// are generated by `bal grpc --input rental.proto --output .`
// Match this file's names to whatever the generated _pb.bal stub calls them.

map<Property> properties = {};   // keyed by property_id
map<Booking> bookingCart = {};   // pending bookings, keyed by booking_id
map<Booking> confirmedBookings = {}; // keyed by booking_id
map<User> users = {};            // keyed by user_id

int propertyCounter = 0;
int bookingCounter = 0;

service "RentalService" on new grpc:Listener(9090) {

    // --- Simple RPCs ---

    remote function add_property(Property value) returns PropertyResponse|error {
        // TODO: generate a property_id, store in `properties`, return it
    }

    remote function update_property(Property value) returns PropertyResponse|error {
        // TODO: look up by property_id, update fields, error if not found
    }

    remote function remove_property(PropertyIdRequest value) returns PropertyList|error {
        // TODO: remove from `properties`, return the host's remaining list
    }

    remote function search_property(PropertyIdRequest value) returns PropertyResponse|error {
        // TODO: return the property, or a "Not Available" message if missing
    }

    remote function book_property(BookingRequest value) returns BookingCartResponse|error {
        // TODO: basic validation (check_out after check_in), add to bookingCart as PENDING
    }

    remote function confirm_booking(ConfirmBookingRequest value) returns BookingConfirmation|error {
        // TODO:
        // 1. verify no date overlap with confirmedBookings for this property
        // 2. calculate total_cost = price_per_night * nights
        // 3. move from bookingCart to confirmedBookings, return confirmation
    }

    // --- Client streaming ---

    remote function create_users(stream<User, grpc:Error?> clientStream) returns UserCreationResponse|error {
        // TODO: iterate clientStream, store each User in `users`, count them,
        // return one UserCreationResponse once the stream ends
    }

    // --- Server streaming ---

    remote function list_available_properties(RentalServiceListAvailablePropertiesCaller caller, PropertyFilter value) returns error? {
        // TODO: foreach property in `properties` matching the filter,
        // check caller->sendProperty(p); then check caller->complete();
    }
}
