import ballerina/grpc;
import ballerina/uuid;
import ballerina/log;
import ballerina/time;


// NOTE: Property, PropertyResponse, User, etc. and the *Caller types below
// are generated by `bal grpc --input rental.proto --output .`
// Match this file's names to whatever the generated _pb.bal stub calls them.

map<Property> properties = {};   // keyed by property_id
map<Booking> bookingCart = {};   // pending bookings, keyed by booking_id
map<Booking> confirmedBookings = {}; // keyed by booking_id
map<User> users = {};            // keyed by user_id

int propertyCounter = 0;
int bookingCounter = 0;

// KEEP THIS FUNCTION HERE
function nightsBetween(string checkIn, string checkOut) returns int|error {
    time:Utc inUtc = check time:utcFromString(
        checkIn + "T00:00:00.00Z"
    );

    time:Utc outUtc = check time:utcFromString(
        checkOut + "T00:00:00.00Z"
    );

    decimal diffSeconds = time:utcDiffSeconds(outUtc, inUtc);

    return <int>(diffSeconds / 86400);
}

service "RentalService" on new grpc:Listener(9090) {

     // add_property
remote function add_property(Property req) returns PropertyResponse|error {

    string propertyId = uuid:createType4AsString();

    Property newProperty = {
        property_id: propertyId,
        property_name: req.property_name,
        location: req.location,
        property_type: req.property_type,
        price_per_night: req.price_per_night,
        status: req.status
    };

    properties[propertyId] = newProperty;

    log:printInfo("Property added: " + propertyId);

    return {
        property: newProperty,
        message: "Property registered successfully"
    };
}



    remote function update_property(Property value) returns PropertyResponse|error {
        // TODO: look up by property_id, update fields, error if not found
    }

    //  remove_property
remote function remove_property(PropertyIdRequest req) returns PropertyList|error {

    Property? target = properties[req.property_id];

    if target is () {
        return error("Property with id " + req.property_id + " not found");
    }

    string region = target.location;

    _ = properties.remove(req.property_id);

    log:printInfo("Property removed: " + req.property_id);

    Property[] remaining = [];

    foreach Property p in properties {
        if p.location == region && p.status == "AVAILABLE" {
            remaining.push(p);
        }
    }

    return {
        properties: remaining
    };
}

    remote function search_property(PropertyIdRequest value) returns PropertyResponse|error {
        // TODO: return the property, or a "Not Available" message if missing
    }

    remote function book_property(BookingRequest value) returns BookingCartResponse|error {
        // TODO: basic validation (check_out after check_in), add to bookingCart as PENDING
    }


//confirm a booking
remote function confirm_booking(ConfirmBookingRequest value)
        returns BookingConfirmation|error {

    // 1. Find the booking in the booking cart
    Booking? cart = bookingCart[value.booking_id];

    if cart is () {
        return {
            booking_id: value.booking_id,
            total_cost: 0.0,
            status: "REJECTED"
        };
    }

    // 2. Find the property
    Property? property = properties[cart.propertyId];

    if property is () {
        _ = bookingCart.remove(value.booking_id);

        return {
            booking_id: value.booking_id,
            total_cost: 0.0,
            status: "REJECTED"
        };
    }

    // 3. Check if the property is available
    if property.status != "AVAILABLE" {
        _ = bookingCart.remove(value.booking_id);

        return {
            booking_id: value.booking_id,
            total_cost: 0.0,
            status: "REJECTED"
        };
    }

    // 4. Check that check-out is after check-in
    int nights = check nightsBetween(
        cart.checkIn,
        cart.checkOut
    );

    if nights <= 0 {
        _ = bookingCart.remove(value.booking_id);

        return {
            booking_id: value.booking_id,
            total_cost: 0.0,
            status: "REJECTED"
        };
    }

    // 5. Check for overlapping confirmed bookings
    foreach Booking confirmed in confirmedBookings {

        if confirmed.propertyId == cart.propertyId {

            if cart.checkIn < confirmed.checkOut &&
               cart.checkOut > confirmed.checkIn {

                _ = bookingCart.remove(value.booking_id);

                return {
                    booking_id: value.booking_id,
                    total_cost: 0.0,
                    status: "REJECTED"
                };
            }
        }
    }

    // 6. Calculate total cost
    float totalCost =
        property.price_per_night * <float>nights;

    // 7. Update the booking
    cart.totalCost = totalCost;
    cart.status = "CONFIRMED";

    // 8. Remove booking from cart
    _ = bookingCart.remove(value.booking_id);

    // 9. Add booking to confirmed bookings
    confirmedBookings[value.booking_id] = cart;

    log:printInfo("Booking confirmed: " + value.booking_id);

    // 10. Return confirmation
    return {
        booking_id: value.booking_id,
        total_cost: totalCost,
        status: "CONFIRMED"
    };
}

    // --- Client streaming ---

    remote function create_users(stream<User, grpc:Error?> clientStream) returns UserCreationResponse|error {
        // TODO: iterate clientStream, store each User in `users`, count them,
        // return one UserCreationResponse once the stream ends
    }

    // --- Server streaming ---

    remote function list_available_properties(RentalServicePropertyCaller caller, PropertyFilter value) returns error? {
    // TODO: foreach property in `properties` matching the filter,
    // check caller->sendProperty(p); then check caller->complete();
}
}
